### PR TITLE
Add metadata to titanic

### PR DESCRIPTION
**Pull request by praneelc**
Updated metadata.yaml
Source verification: [https://colab.research.google.com/drive/1HVivcFv5wHQ182ntPFhs5wOkMSuS3apN#scrollTo=AyQQlont_-V-](https://colab.research.google.com/drive/1HVivcFv5wHQ182ntPFhs5wOkMSuS3apN#scrollTo=AyQQlont_-V-)

### CODE REVIEW

**Comment by praneelc** [comment]
Nose test seems to be failing because of the colons in line 8, which has the title of the source publication from which most of the data originated. The colons are part of the title, so if the name of the book is removed, the test will probably progress further, but I don't know if there's some alternative method that would allow the title to be kept.

**Comment by trangdata** [comment]
Hmm... I don't think we should use this titanic dataset with only three variables. I suggest we replace the existing dataset with one from https://www.openml.org/d/40945. @weixuanfu

**Comment by weixuanfu** [comment]
Sounds good.

**Comment by weixuanfu** [comment]
Same here. I think a recent force merging on master branch created a lot of conflicts and recreating a new branch should make a new clear PR.

**Pull request closed without merging**
