### PR TITLE
Add metadata for wine_quality_white

### PR DESCRIPTION
**Pull request by trangdata**
Work in progress.

Add metadata for `wine_quality_white`.

- [x] Update the information on the dataset's metadata.yaml file. 

- [x] Verify the source for the dataset: [Check here.](https://colab.research.google.com/drive/1z_aFLydv2xMjDWwYIGGbW5N8_XFraysT?usp=sharing)

### CODE REVIEW

**Comment by trangdata** [comment]
There are a few rows in the original source that is not in the dataset (see [here](https://colab.research.google.com/drive/1z_aFLydv2xMjDWwYIGGbW5N8_XFraysT?usp=sharing)).

In general, I suspect a lot of other checks will be similar as well (e.g. minor floating-point differences between the dataframes). What should we do in these cases? Should we add back these rows? @weixuanfu @lacava

**Review by lacava — APPROVED** [review]
:+1:

**Comment by trangdata** [comment]
@weixuanfu Since we agree on adding the rows back in, could you help me do that so we can merge, please? 🙏

**Comment by weixuanfu** [comment]
I will do that next week with adding an parameter (maybe called 'allow_na') in `fetch_data` to control it to export dataframe with or without NAs.

**Comment by lacava** [comment]
> I will do that next week with adding an parameter (maybe called 'allow_na') in fetch_data to control it to export dataframe with or without NAs.

I like this idea!

**Pull request merged**
