### PR TITLE
#170 Initial commit of two datasets extracted from the Nikuradse paper (Flow in Rough Pipes).

### PR DESCRIPTION
**Pull request by gkronber**
For issue #170

### CODE REVIEW

**Comment by trangdata** [comment]
Thank you for contributing these datasets, @gkronber. 🚀 

Any chance you could merge EpistasisLab/master to this branch again, please? It seems that the dataset update action didn't run on this fork, so I (hopefully) fixed this.

**Comment by gkronber** [comment]
@trangdata thanks for looking into the failed workflow. I merged master

**Comment by trangdata** [comment]
@gkronber the update dataset metadata action should have run on your [heal-research:170_Nikuradse](https://github.com/heal-research/pmlb/tree/170_Nikuradse) fork when you added the new datasets. I'm not sure why it did not. Any chance you disabled GH Actions on the fork?

**Comment by trangdata** [comment]
Thank you for merging again @gkronber. So it looks like this action [ran](https://github.com/heal-research/pmlb/actions/runs/4234099678/jobs/7355929353)! However, it doesn't detect any changed dataset. I'll have to look back at the code.

```
Run python -m pmlb.update_dataset_files
changed datasets: []
changed metadata: []
```

**Comment by trangdata** [comment]
@gkronber Could you create an empty commit to your branch  [heal-research:170_Nikuradse](https://github.com/heal-research/pmlb/tree/170_Nikuradse) and include in your commit message `[update_all_datasets]` please? So:

```
git commit --allow-empty -m "[update_all_datasets]" 
```

**Comment by trangdata** [comment]
This is very peculiar! Not the behavior I was expecting at all. The action shouldn't overwrite the manual reviews of banana and titanic. This is likely due to the reviewers not adding their name to the first line, but still, it should update the metadata.yaml file for your two new datasets. Thanks for being patient @gkronber. We may need to just close this PR and redo.

**Comment by gkronber** [comment]
@trangdata no worries, I'm ready to continue with this.

Could you please be a bit more specific. Do you mean we close this PR, I branch master again in my fork and then I redo my first two commits to add the dataset?

Please let me know when you are ready with your changes so that the workflow does not change existing datasets.

**Comment by trangdata** [comment]
> Could you please be a bit more specific. Do you mean we close this PR, I branch master again in my fork and then I redo my first two commits to add the dataset?

So I think we would close this PR, merge EpistasisLab/pmlb/master to heal-research/pmlb/master (after my minor fix in #174), checkout a new branch, say, heal-research/pmlb/Nikuradse, add your two datasets. Once you add these datasets, an action should run to create metadata.yaml for each dataset. I will review the PR.

Before we proceed, though, could you help me understand a little more: did you change anything in your repository settings at heal-research/pmlb? I'm still unsure why the update dataset metadata action didn't run the first time.

**Comment by gkronber** [comment]
> Before we proceed, though, could you help me understand a little more: did you change anything in your repository settings at heal-research/pmlb? I'm still unsure why the update dataset metadata action didn't run the first time.

You guessed correctly that github actions were deactivated. I had to manually activate them.

**Comment by gkronber** [comment]
We retry via a new PR.

**Pull request closed without merging**
