### PR TITLE
Generate metadata for classification datasets

### PR DESCRIPTION
**Pull request by ramhiser**
Python script to generate metadata for classification data sets. Metadata are given in `classification_datasets_pmlb.tsv` -- my goal was to match the regression metadata formatting as much as possible.

I make a couple of assumptions:

1. Working directory is `/datasets/classification` when Python script is executed
2. `pmlb` is already installed

### CODE REVIEW

**Comment by rhiever** [comment]
Much appreciated, @ramhiser!

**Comment by ramhiser** [comment]
@rhiever just realized that the `MinorityClassSize` and `MajorityClassSize` are swapped. going to push a quick fix.

**Comment by rhiever** [comment]
OK

**Comment by ramhiser** [comment]
pushed another PR #17 to apply the fix

**Pull request merged**
