### PR TITLE
Regression benchmarks from openML

### PR DESCRIPTION
**Pull request by weixuanfu**
Add 120 benchmarks from openML.
related issue #6

### CODE REVIEW

**Comment by weixuanfu** [comment]
I just found that the `target` output from openml-python api is strangely convert to integer, which is not right. I need double-check these benchmarks.

**Comment by weixuanfu** [comment]
the dtype issue is fixed.

**Comment by rhiever** [comment]
We should organize these datasets better. Regression datasets should go into `datasets/regression/`, and classification datasets should go into `datasets/classification/`.

Also, please change all `class` column names to `target` in the classification datasets. That should also be fixed in the docs.

**Comment by weixuanfu** [comment]
OK, sounds good. I will fix it.

**Comment by weixuanfu** [comment]
I reorganized these datasets

**Comment by rhiever** [comment]
FYI I changed the base to the dev branch.

**Comment by weixuanfu** [comment]
Oh, right. Sorry about wrong branch.

**Comment by rhiever** [comment]
No problem. It's all merged on the dev branch. When I get more time I will work on a roll-out and update for PMLB.

**Pull request merged**
