### PR TITLE
add filter_datasets to pmlb.py

### PR DESCRIPTION
**Pull request by praneelc**
resubmitting as PR to master branch

### CODE REVIEW

**Comment by weixuanfu** [comment]
@trang1618 if contributor make a PR from a forked repo, the 1st CI check should failed (like [this](https://github.com/EpistasisLab/penn-ml-benchmarks/pull/117/checks?check_run_id=1098423756)) maybe we should remove any `git push` or deploy step in CI for PR.

**Comment by trangdata** [comment]
> if contributor make a PR from a forked repo, the 1st CI check should failed (like this) maybe we should remove any git push or deploy step in CI for PR.

There should be a way around this. The reason I wanted to generate these files in PR is to avoid adding anything straight to master without reviewing. Let's explore our options a bit...

**Comment by trangdata** [comment]
Another option is to trigger the build on push events of the forked repo.

**Comment by trangdata** [comment]
I believe this has now been fixed in #130.

@praneelc Could I ask you to re-submit this PR one more time, please? Thank you for being patient with us as we figure out the workflow.

**Pull request closed without merging**
