### PR TITLE
Add metadata for poker

### PR DESCRIPTION
**Pull request by trangdata**
[Google collab notebook](https://colab.research.google.com/drive/1h7mCC7WH-2n0RPMWdwC73dyN-Crk_BZ-#scrollTo=93XXJBQdhlCQ)

Notes from the notebook: 
- [x] one missing row in PMLB
- [x] ~both source and PMLB have more than 2000 duplicated rows that should probably be eliminated. What do you think @weixuanfu?~

### CODE REVIEW

**Comment by weixuanfu** [comment]
Good catch! But I think we should keep those duplicated rows like its source.

**Comment by trangdata** [comment]
@weixuanfu  I disagree. I think we should stay close to the source but also try our best to eliminate potential issues for the user when they use the data to train their models (just like how we decided to remove the 7th column of bupa). We should note in our metadata description that we removed duplicated rows. Also, we have over 1 million rows for these datasets. Removing ~ 2000 should still leave us with a lot of records, right?

**Comment by weixuanfu** [comment]
I think this case is different with 7th column of bupa. I agree that ~2000 rows are duplicated records but I think they should challenge some ML algorithms to handle them. I think we can add a option to drop duplicated rows like we added `drop_na` option.

**Comment by trangdata** [comment]
> they should challenge some ML algorithms to handle them

I don't think this is a "challenge" for algorithms. If some of these duplicates happen to be in both training and testing sets, we have a case of overfitting.

**Comment by trangdata** [comment]
After our discussion today, we agree that we cannot verify the nature of the duplicated rows. Therefore, we will keep them in the dataset. However, I will make a note in the description field of the metadata.

**Comment by trangdata** [comment]
@weixuanfu  Could you help resolve the conflicts and add one missing row, please?

**Comment by weixuanfu** [comment]
OK, I will fix that.

**Comment by weixuanfu** [comment]
Hmm, I think we should remove deploy step in PR, which is main reason of those conflicts.

**Comment by trangdata** [comment]
> Hmm, I think we should remove deploy step in PR, which is main reason of those conflicts.

Oh I see. OK.

**Pull request merged**
