### PR TITLE
PMLB1.0 release

### PR DESCRIPTION
**Pull request by weixuanfu**

### CODE REVIEW

**Review by trangdata — APPROVED** [review]
💯  🙌  ✨

**Comment by weixuanfu** [comment]
The reason of failed CI is that some dataset names were changed in PMLB2.0 but `updated_dataset` included original names in master branch so those dataset could not be found. 

Maybe a hash tag for each dataset is needed in the further version of pmlb for checking updated dataset.

**Comment by trangdata** [comment]
I don't think we need hash values. I would like to automatically generate `dataset_names` in CI and get rid of the `data_type` in [old url](https://github.com/EpistasisLab/penn-ml-benchmarks/blob/5c420dbca0e21f40faea5cdab741198a320bce4a/pmlb/pmlb.py#L100). Are existing users aware of this breaking change?

**Comment by weixuanfu** [comment]
Yep, we have warning message for url/dataset name changes.

**Pull request merged**
